language: python
python:
    - "2.6"
    - "2.7"
    - "3.2"
    - "3.3"
    - "3.4"
# command to install deps
install:
    - pip install -r requirements.txt
# comment to run tests
script: nosetests --with-doctest
